baseURL: 'https://subversive-eu.github.io/hugo-subversive/'
title: Subversive
author: subversive.eu
paginate: 5
languageCode: en
DefaultContentLanguage: en
enableInlineShortcodes: true
theme: hugo-subversive

enableRobotsTXT: true

# I use this because problems with my github pages.
canonifyURLs: true

params:
  env: production # enable google analytics, opengraph, twitter-cards and schema.
  description: 'Theme Subversive- https://github.com/subversive-eu/hugo-subversive'
  author: subversive.eu
  keyword: 'hugo, hugo-theme, subversive'
  ShowReadingTime: true
  contentTypeName: posts
  ShowShareButtons: true
  comments: false

  homeInfoParams:
    Title: "Rhello \U0001F44B"
    Content: Welcome to the Subversive Theme Demo

  socialIcons:
    - name: rss
      url: 'https://subversive-eu.github.io/hugo-subversive/posts/index.xml'
    - name: github
      url: 'https://github.com/subversive-eu/hugo-subversive'

  menu:
    - name: home
      url: '/'
      weight: 5
    - name: info
      url: /about/
      weight: 10
#    - name: tag
#      url: /tags/
#      weight: 15
    - name: categorie
      url: /categories/
      weight: 20
#    - name: serie
#      url: /series/
#      weight: 25
    - name: archive   
      url: /archives/
      weight: 30

sitemap:
  changefreq: dayly
  filename: sitemap.xml
  priority: 0.5

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1

taxonomies:
  category: categories
#  tag: tags
#  series: series

privacy:
  vimeo:
    disable: false
    enableDNT: true
    simple: false
  twitter:
    disable: false
    enableDNT: true
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

# RSS feed
rsslimit: 5

# testing:
outputs:
  home:
  - HTML
  - RSS
outputsFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "/feed/"